{% set name = "conda-export" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/olegtarasov/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 73fea89cfeb2ec132292eb79d135f165a6d3cc9e8d80c2e3a58f6c3a5c9f6db5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - conda-export = conda_export:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - pip
    - conda
    - networkx

test:
  commands:
    - conda-export -h

about:
  home: https://github.com/olegtarasov/conda-export
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Platform agnostic conda environment export'
  description: |
    An alternative to `conda env export` that helps create portable environment 
    specifications with minimum number of packages. 

    Conda-export creates environment specifications which contain only top-level 
    (non-transient) dependencies. It tries to minimize specific version information and 
    total number of packages, so that the resulting spec maximizes [upgradability](https://pythonspeed.com/articles/conda-dependency-management/#three-kinds-of-dependency-specification).
    At the same time, it respects specific package versions that were used while creating 
    the environment. If, at some point, you installed a package with explicit version (e. g. 
    `conda install pytorch=1.9.0`), `conda-export` will include this specific version in 
    the resulting spec file.
  doc_url: https://github.com/olegtarasov/conda-export
  dev_url: https://github.com/olegtarasov/conda-export

extra:
  recipe-maintainers:
    - olegtarasov
